### ISSUE TITLE
Kalender Ansicht

### ISSUE THREAD

**Issue by Schrottpage** [neuland-ingolstadt/THI-App#10]
Als Studierender verliert man öfters den Überblick über sein Leben. So werden auch schnell mal wichtige Hochschultermine Vergessen. Hier können wir Intervenieren und mit einem übersichtlichen Kalender das Hochschulleben erleichtern. 

Elemente für den Kalender:

- Prüfungen
- Rückmeldungszeiträume
- Stundenplan

**Comment by M4GNV5** [comment]
https://www.thi.de/fileadmin/daten/studienangelegenheiten/Allgemeines/Semestertermine_Studium_WS_2020_2021_SS_2021_23.10.2020.pdf
