### ISSUE TITLE
Mark vegetarian and vegan menu items as such

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/THI-App#109]

**Comment by M4GNV5** [comment]
The max-manager mensa XML provides this information only via the `piktogramme` which contains one or more `img` html tags linking to one of the images included in the footer of https://www.werkswelt.de/index.php?id=eich&setlang=de.
There also seem to be at least two new images not listed: [gluten free](https://www.max-manager.de/daten-extern/sw-erlangen-nuernberg/icons/Gf.png?v=1) and [low carbon footprint](https://www.max-manager.de/daten-extern/sw-erlangen-nuernberg/icons/CO2.png?v=1).

We could think about adding these images to our App? Or rather use flat fontawesome-like icons. Sadly fontawesome does not provide food/animal icons.

**Comment by alexhorn** [comment]
The original images would not fit in, we should either include the information as text or use our own icons
