### ISSUE TITLE
Display bug with the retro theme

### ISSUE THREAD

**Issue by Schrottpage** [neuland-ingolstadt/THI-App#11]
The retro theme font is too big to be displayed correctly on a mobile phone

**Comment by Schrottpage** [comment]
![Screenshot_20210120-190802](https://user-images.githubusercontent.com/39926202/105216667-2a002d80-5b53-11eb-9e84-8dc12b9a12a3.jpg)

**Comment by M4GNV5** [comment]
Maybe an easy fix would be to rename it back to `Cyberpunk`, but append a `(might contain bugs)`? :laughing:

**Comment by Schrottpage** [comment]
That sounds like a case for "schlechte.software" to me 🙃
