### ISSUE TITLE
Display of the grade point average

### ISSUE THREAD

**Issue by Schrottpage** [neuland-ingolstadt/THI-App#12]
It would be great if you could see the grade point average.

**Comment by M4GNV5** [comment]
Calculating the avrage grade is often not a simple `sum(grades) / len(grades)` but rather a complex formula with some grades counting more than others. Currently the THI API does not provide the average grade as displayed in primuss.

So our best bet is to wait for #7 alternatively we could search for a formula source for each course of study.
