### ISSUE TITLE
Prettier calendar view

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/THI-App#20]
Implement multiple calendar views similar to what Apple and Google Calendar offer. The user should be able to switch between a list view (which we already have) and a week view.

**Comment by M4GNV5** [comment]
Here are some components we could use:
- https://www.npmjs.com/package/react-big-calendar best option i guess?
- https://fullcalendar.io/ similar to above but with pricing model (free version is MIT licensed though?)
- https://ej2.syncfusion.com/react/documentation/schedule/views/ weird proprietary license

**Comment by M4GNV5** [comment]
None of the above seem to look good on mobile. fullcalendar is very popular, but only seems to care about desktop users. There is [this stackoverflow thread](https://stackoverflow.com/questions/43256869/how-to-make-fullcalendar-responsive), but there does not seem to be a good solution to the problem.

There also exists [this list of js calendars](https://flatlogic.com/blog/top-javascript-calendar-plugins/) but none of them seems to support mobile while also being FOSS.

**Comment by M4GNV5** [comment]
I guess we can close this as there are no calendar components available and we already improved our timetable view with the new weekly-swipy-tab-layout-thing.
