### ISSUE TITLE
Encrypt saved credentials using CryptoKeys

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/THI-App#22]
The credentials are needed to refresh the users session when it runs out. Since there is no credential storage available to a PWA, we could encrypt them using a non-extractable key and store the ciphertext in localStorage.

https://developer.mozilla.org/en-US/docs/Web/API/CryptoKey

**Comment by M4GNV5** [comment]
https://stackoverflow.com/questions/52276862/web-crypto-api-is-a-non-exactrable-cryptokey-in-indexeddb-safe-enough-against
