### ISSUE TITLE
Publish app in app stores

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/THI-App#32]
Package the app using Apache Cordova (?) and publish it to the Apple App Store and Google Play Store.

**Comment by M4GNV5** [comment]
This looks like an easy enough way to pack the app as a native app:
https://broddin.be/english/packaging-nextjs-capacitor/

Android App publishing should be straightforward, but we probably need a Mac user for building an iOS App.

**Comment by M4GNV5** [comment]
Using above tutorial i was able to generate the following signed android app bundle, which should be play-store ready: https://i.m4gnus.de/1ade0c.aab

I guess this leaves the following TODO for this issue:
- [ ] Publish in F-Droid
- [ ] Create a Play Store developer account (price?)
- [ ] Publish the App to the Play Store
- [ ] Create an Apple Developer account (price? free for non-profits?)
- [ ] Publish the App to the App Store

**Comment by M4GNV5** [comment]
Progress on this issue is now tracked in #82, #83, #84
