### ISSUE TITLE
Switch between light and dark theme automatically

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/THI-App#35]
At sunset, my phone automatically switches to dark mode, but the app keeps the light theme. Our app should honor the system preferences and automatically switch between the light and dark theme. Maybe we could merge the light and dark themes into a single "default" theme?

**Comment by M4GNV5** [comment]
I guess a good first start is to have the default or dark theme selected based on the `prefers-color-scheme` media query when a new users first opens the site.

https://gosink.in/javascript-css-toggle-dark-light-theme-based-on-your-users-preferred-scheme/

**Comment by alexhorn** [comment]
You can add add listeners to `window.matchMedia` to look for color scheme changes during runtime:

https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia
