### ISSUE TITLE
Rotation option for the room plan map

### ISSUE THREAD

**Issue by Schrottpage** [neuland-ingolstadt/THI-App#36]
Rotation option for the room plan map like on google maps etc.

**Comment by M4GNV5** [comment]
Rotating a map is not supported by leaflet: https://github.com/Leaflet/Leaflet/issues/268
If we really want this i guess we can move to a different library or try using [the leaflet fork with rotation support](https://github.com/va2ron1/Leaflet), but i dont think using a forked version which does not receive updates and bugfixes from upstream is a good idea.

So: Do we really need this feature in the neuland app?
