### ISSUE TITLE
Discord faculty link in the THI app

### ISSUE THREAD

**Issue by Schrottpage** [neuland-ingolstadt/THI-App#38]
We could assign the specific Discord server link to people based on their faculty.

**Comment by M4GNV5** [comment]
I don't think there is information on what faculty a user belongs to somewhere in the API data. An easy alternative would be to create a list of all course of studies and map them to their faculties. A users course of study is available via [persdata](https://github.com/neuland-ingolstadt/THI-App/blob/develop/thi-rest-api.md#personal-data).
