### ISSUE TITLE
Timetable entry details

### ISSUE THREAD

**Issue by M4GNV5** [neuland-ingolstadt/THI-App#42]
sending `details=1` in the timetable api call allows to retrieve HTML code with `inhalt`, `literatur` and `ziel`. We could provide this as additional information when clicking a lecture in the timetable.
From the code perspective it would be similar to how we provide additional information to upcoming exams.

**Comment by alexhorn** [comment]
Fixed in a1fa128381de4bf5e8e89468b76fb35a53d581e8.
