### ISSUE TITLE
Use `Intl.DateTimeFormat` and `Intl.RelativeTimeFormat` where possible in `date-utils.js`

### ISSUE THREAD

**Issue by M4GNV5** [neuland-ingolstadt/THI-App#49]
In [date-utils.js](https://github.com/neuland-ingolstadt/THI-App/blob/develop/rogue-thi-app/lib/date-utils.js) we have a lot of custom code for datetime formatting. However most browsers provide such functionality already via the [`Intl`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) object.
Especially our [`formatAbsoluteFriendlyRelativeTime`](https://github.com/neuland-ingolstadt/THI-App/blob/develop/rogue-thi-app/lib/date-utils.js#L78-L106) looks basically like a german-only re-implementation of [`Intl.RelativeTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/RelativeTimeFormat)

**Comment by alexhorn** [comment]
Luxon is a great wrapper around the `Intl` API: https://moment.github.io/luxon/

**Comment by M4GNV5** [comment]
The goal of this issue is to reduce code complexity by using built in tools. I think pulling in another dependency has the opposite effect.

**Comment by alexhorn** [comment]
`Intl` has no way of parsing strings, which is where a lot of our date handling complexity comes from. Luxon on the other hand allows you to parse dates similar to what you can do with `DateTimeFormatter` in Java.

**Comment by M4GNV5** [comment]
`date-utils.js` excusively handels date formatting not parsing.
I dont think we have any central date parsing utility? It looks like most of the time it boils down to concating a date and a time string to obtain a ISO-compatible date/time string.
