### ISSUE TITLE
Animate tab transitions

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/THI-App#50]
Example: https://kstatic.googleusercontent.com/files/fdb2ac963ec4367bed4f06fc1ea2e6f84b0630f63a3bb0cf162de0522956338b33e686428707b0e6c50d700d4887cd08455932a2ebe34a8f5cb7297f928a4eeb

**Comment by M4GNV5** [comment]
Implemented by d0f8f3fc6974ef80bd9409d62f1cd91af61a4be2, 9876bc40932926d6ccc2a64cb65b66898b743d37 and cc07777dd76bcdac4c09764b894d28cca05c7d8f
