### ISSUE TITLE
Broken train stations 

### ISSUE THREAD

**Issue by Schrottpage** [neuland-ingolstadt/THI-App#58]
The main train station and the north train station are currently broken. However, the Audi train station works.
![Screenshot_20210606-163635](https://user-images.githubusercontent.com/39926202/120929308-dbf65b80-c6e8-11eb-8e14-9478d5cd5ae8.jpg)
![Screenshot_20210606-163649](https://user-images.githubusercontent.com/39926202/120929309-dc8ef200-c6e8-11eb-8769-0e31dff4e32a.jpg)

**Comment by M4GNV5** [comment]
It works fine for me when i try it now. Maybe it was a temporary disturbance with the bahn service? Can you confirm it works again @Schrottpage?

**Comment by Schrottpage** [comment]
yes works again. But maybe you should note that it doesn't happen more often. Or at least create a nicer error message for invalid data from DB.

**Comment by alexhorn** [comment]
It's broken again due to this entry:
![image](https://user-images.githubusercontent.com/13948008/121774593-5e689a80-cb83-11eb-9c3e-7af669ff6b95.png)
