### ISSUE TITLE
Room plan

### ISSUE THREAD

**Issue by M4GNV5** [neuland-ingolstadt/THI-App#6]
The official App has a room plan based on OSM and GeoServer.

Steps:
- [X] extract room data from [the THI geoserver](https://map.thi.de/geoserver/web/)
- [x] implement a (leaflet.js based?) map/room rendering
- [ ] allow to click on rooms in `/room`, `/exams` and `/library` and show the room highlighted in the map

**Comment by alexhorn** [comment]
Room data is available at `https://map.thi.de/geoserver/wfs?service=wfs&version=2.0.0&request=GetFeature&outputFormat=application%2Fjson&typeName=mythi%3ATHI_Raeume`

Other available layers include `mythi:Objekte`, `mythi:THI_Gebaeude` and `mythi:THI_Baustellen`
