### ISSUE TITLE
Integrate ophase.neuland.app into the room plan

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/THI-App#60]
We could integrate the tour at https://ophase.neuland.app/tour into our room plan.

**Comment by FabianSimonGross** [comment]
Please make it toggleable because for older students it might get annoying.

**Comment by FabianSimonGross** [comment]
After some discussion with @Schrottpage @chiaragambirasio we came to a conclusion, that Ophase should rather be linked than integrated into the room plan due to usability and annoyance of older students.
