### ISSUE TITLE
Failure if you don't have any exams

### ISSUE THREAD

**Issue by Schrottpage** [neuland-ingolstadt/THI-App#63]
If you don't take an exam, you get an error message all the time
![Uploading Screenshot_20210629-205908.jpg…]()

**Comment by M4GNV5** [comment]
The screenshot is missing, it looks like you submitted the issue while it was still uploading :smile:

**Comment by Schrottpage** [comment]
![Screenshot_20210629-205908__01](https://user-images.githubusercontent.com/39926202/123919689-79118080-d985-11eb-9dec-37c95cee059c.jpg)
![Screenshot_20210629-205843__01](https://user-images.githubusercontent.com/39926202/123919690-7a42ad80-d985-11eb-8092-ba7f88004e88.jpg)

**Comment by alexhorn** [comment]
Fixed in c4b236fe50711bb027692621905ad90182746a2d and 1325629b48dda9ac3ecadfa5a158805c17857b3b.
