### ISSUE TITLE
Develop a "Donation"/"Support us" Fuction to PayPal or anythin

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/THI-App#69]
Implement a Donation System to PayPal so we can Test/Try/Use if we have a audience who would support us.
It's for making the whole thing sustain itself

**Comment by M4GNV5** [comment]
I would vote against this feature. We currently do not have a Paypal etc. and it makes it somewhat needy/unprofessional.

Maybe a button "Become a member" or even "Support us by becoming a member" could be added to the Imprint where we already list links to this Github repo and our website.
