### ISSUE TITLE
Add Room Map Support for the new Campus in Neuburg

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/THI-App#74]
I'm going to inquire the Room Plan from THI so we can develop this function rather soon.
So we can add the support before semester start.

**Comment by M4GNV5** [comment]
The Campus Neuburg building is already included in the room map:

![](https://i.m4gnus.de/1afa15.png)

All room data is available from the THI Geoserver (see issue #6), we simply extracted the room data from it in JSON format.
We can export the data again every time new rooms become available and/or automate this process.

**Comment by FabianSimonGross** [comment]
Thats not the new Campus. Thats an Institute.

The new Building is: 
![grafik](https://user-images.githubusercontent.com/81598210/132721344-546c0ee6-7775-47b4-9f50-785aa75fb199.png)

**Comment by M4GNV5** [comment]
The THI Geoserver reports `totalFeatures: 897` which is exactly the number our [rooms.json](https://github.com/neuland-ingolstadt/THI-App/blob/develop/rogue-thi-app/data/rooms.json) file includes, thus it looks like we are up-to-date.

Maybe the new Campus is yet to be mapped by the THI itself and we simply have to wait.

My proposal is to add a step in the Dockerfile which fetches an up-to-date version of the roomplan.

**Comment by FabianSimonGross** [comment]
Sounds plausible to add a step in the Dockerfile. :)

**Comment by alexhorn** [comment]
> My proposal is to add a step in the Dockerfile which automatically fetches an up-to-date version of the roomplan.

Next.js has a `getStaticProps` method which we can implement to fetch data at build time

**Comment by M4GNV5** [comment]
I've had some problems when using the `getStaticProps`, `getInitialProps` and `getServerSideProps` together with `next export` (e.g. for building an android/iOS app) as some of these functions might fail.

It might work for this case though, similarly to how the `getInitialProps` in `imprint.js` doesnt seem to cause problems. Feel free to send a pull request.
