### ISSUE TITLE
add parking spaces in Neuburg

### ISSUE THREAD

**Issue by Schrottpage** [neuland-ingolstadt/THI-App#75]
THI is expanding its campus to Neuburg. In the Neuland.app, students should be able to see the parking lots in the city of Neuburg.

https://www.neuburg-donau.de/leben/parken-in-neuburg

**Comment by alexhorn** [comment]
Is there a page where you can see the amount of unoccupied parking spots in Neuburg?

**Comment by DanielMehlber** [comment]
How about a dropdown menu for selecting a campus (Ingolstadt or Neuburg)? 
But then we also have to extend bus, train and e-car with that functionality

**Comment by FabianSimonGross** [comment]
> Is there a page where you can see the amount of unoccupied parking spots in Neuburg?

https://www.neuburg-donau.de/leben/parken-in-neuburg#collapse-ladeplaetze-fuer-elektroautos

Ladeplätze für Elektroautos

**Comment by M4GNV5** [comment]
Live parking data does not seem to be available online, thus we cannot implement this issue.

We could add charging stations in Neuburg, but that would be a separate issue
