### ISSUE TITLE
Query not possible error, -102

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/THI-App#78]
![grafik](https://user-images.githubusercontent.com/81598210/133488282-d30ce523-9357-4707-8e3d-22c2d0cc6c73.png)
![grafik](https://user-images.githubusercontent.com/81598210/133488341-ebfcdbef-3dda-425e-8069-67f8d0adda5f.png)

**Comment by alexhorn** [comment]
Duplicate of #76
