### ISSUE TITLE
Whazzup Function

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/THI-App#88]
A simple function (now the App is still rather unknown therefore not many Students will use it) where Students can post whats going in Ingolstadt and you can connect. (2 hour long post)

For example I would sit in a Bar with one friend but we want to connect with some other students. In this function you can post Whazzup in the city and well meet with some.

Further rethinking and ideas needed to proceed with this function. (Jodel exists but is not frequently used by thi students afaik)

**Comment by alexhorn** [comment]
Sorry, that's out of scope (and literally a clone of Jodel)
