### ISSUE TITLE
Trouble with course description

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/THI-App#91]
![WhatsApp Image 2021-09-21 at 19 23 20](https://user-images.githubusercontent.com/81598210/134328167-e43151ae-b70d-4ff3-a3bc-8e56ae025e4f.jpeg)
![WhatsApp Image 2021-09-21 at 19 23 21](https://user-images.githubusercontent.com/81598210/134328217-e452bf30-3b18-4367-9390-5455f343034b.jpeg)

Looks like an THI-Side problem not sure?
Can't provide more debug info rn.

**Comment by M4GNV5** [comment]
It works fine for me, so it looks like this is an error specific when trying to retrieve your timetable.

Afaik some functions like PHP's `json_decode` return a stdClass which works somewhat like a associative array (= dict in python / object in js) but isnt identical. So this is probably a programming error in the THI-App Backend

**Comment by M4GNV5** [comment]
I guess we can close this as the problem lies inside the THI backend code?

What courses did you pick exactly? And how does the original THI-App behave? You might want to report this bug directly to the THI with that information.
